services:
  api:
    image: ghcr.io/iam4tart/agentic-crm-support-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db

  ui:
    image: ghcr.io/iam4tart/agentic-crm-support-ui:latest
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env
